version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
